export const FETCH_USERS = "FETCH_USERS";
export const FETCH_EXERCISES = "FETCH_EXERCISES";
export const FETCH_EXERCISES_ERROR = "FETCH_EXERCISES_ERROR";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const LOADING = "LOADING";
